### ISSUE TITLE
运行遇到问题

### ISSUE THREAD

**Issue by breknddone** [Lornatang/MetaSR-PyTorch#2]
我在运行test.py时，发现会报错scale_factor: float = 1.0) -> Any:
TypeError: 'type' object is not subscriptable
不知道是不是python版本的问题，个人版本是python3.7--pytorch1.13
盼解答，谢谢！

**Comment by breknddone** [comment]
报错位置是imgproc.py第589行 scale_factor: float = 1.0) -> Any:

**Comment by Lornatang** [comment]
我是在Ubuntu22.04上，测试没有问题

**Comment by breknddone** [comment]
> 我是在Ubuntu22.04上，测试没有问题

是因为我使用的是windows系统的原因吗？

**Comment by Lornatang** [comment]
如果忽略这个错误，只需要把
```
scale_factor: float = 1.0) -> Any:
```
变成
```
scale_factor: float = 1.0):
```

**Comment by Lornatang** [comment]
我发现了这个问题，正在修复...

**Comment by IrisDinge** [comment]
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    import imgproc
  File "/Code/MetaSR-PyTorch/imgproc.py", line 588, in <module>
    center: tuple[int, int] = None,
TypeError: 'type' object is not subscriptable

我的bug在上面一行， Ubuntu 18

**Comment by Lornatang** [comment]
可注释掉这个类型定义。
