### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by Sugarb0ombs** [Lornatang/MetaSR-PyTorch#3]
运行train.py 的时候 报错
Traceback (most recent call last):
  File "D:\建模\MetaSR-PyTorch-master\train.py", line 357, in <module>
    main()
  File "D:\建模\MetaSR-PyTorch-master\train.py", line 48, in main
    train_prefetcher, test_prefetcher = load_dataset()
                                        ^^^^^^^^^^^^^^
  File "D:\建模\MetaSR-PyTorch-master\train.py", line 156, in load_dataset
    train_prefetcher = CUDAPrefetcher(train_dataloader, config.device)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\建模\MetaSR-PyTorch-master\dataset.py", line 201, in __init__
    self.stream = torch.cuda.Stream()
                  ^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\metaSR\Lib\site-packages\torch\cuda\streams.py", line 34, in __new__
    return super(Stream, cls).__new__(cls, priority=priority, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\metaSR\Lib\site-packages\torch\cuda\_utils.py", line 46, in err_fn
    raise RuntimeError(

RuntimeError: Tried to instantiate dummy base class Stream

**Comment by Lornatang** [comment]
我发现了这个问题，正在修复...
